spring:
  application:
    name: Finance Tracker
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:finance_tracker}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:elec5619p5g1}
    password: ${DB_PASSWORD:financetrackeristhebestprojectforelec5619}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:5622}
      password: ${REDIS_PASSWORD:financetrackeristhebestprojectforelec5619redispw}
      
server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

jwt:
  secret: ${JWT_SECRET:financetrackerTestJWTSecret2025!123456}
  expiration: 86400000

file:
  upload:
    path: ${FILE_UPLOAD_PATH:./uploads/}
  visit:
    path: ${FILE_VISIT_PATH:/resources/}

CORS_DOMAINS_URL: ${CORS_DOMAINS:http://localhost:5173}

app:
  seed:
    enabled: ${APP_SEED_ENABLED:false}
    demo-user:
      username: ${APP_SEED_USERNAME:demo}